
# Dockerfile pour le serveur nginx
FROM nginx:bookworm

# Copier la configuration nginx personnalisée
COPY	conf/nginx.conf /etc/nginx/nginx.conf
COPY	html/index.html /etc/nginx/html/index.html


# Le dossier des fichiers statiques sera monté via un volume
# ou copié via docker-compose

# Exposer le port 80
EXPOSE 443

# Démarrer nginx
CMD ["nginx", "-g", "daemon off;"]