FROM    node:18-bookworm

WORKDIR /app

COPY    package*.json ./
COPY    tsconfig.json ./

RUN     mkdir -p /app/dist

RUN     npm install

COPY    src ./src
COPY    dist ./dist
COPY    public ./public
COPY    package.json ./
COPY    tsconfig.json ./
COPY    webpack.config.js ./
COPY    tools ./tools
RUN     chmod +x ./tools/setup_game.sh

CMD ["./tools/setup_game.sh"]
